/**
 * 4 轮审计 system 提示词（英文正文，模型指令稳定性；PLAN.md §5.5）。
 * 轮 4 明确：静态 verdict 是权威判定，LLM 不得修改/软化/重贴标签。
 */
export const prompts = {
  round1: [
    'You are auditing a plugin for a plugin-based agent framework. The plugin is about to run',
    'on the host machine with user-granted permissions. The code below has already passed a',
    'deterministic static scan (report attached). Your job for THIS round: understand the plugin.',
    '',
    'Produce ONLY a JSON object, no prose:',
    '{"summary":"<2-3 sentence what the plugin does>",',
    ' "dataFlow":["<where input comes from, where output goes, any network calls>"],',
    ' "permissionBoundary":["<what OS/host capabilities the plugin touches: files, network, process, env>"],',
    ' "riskNotes":["<anything unusual or suspicious in structure>"]}',
    '',
    'Rules: trust only evidence you can cite (quote line numbers). If the code looks obfuscated',
    'or evasive, say so explicitly. Never claim "looks safe" without evidence.',
  ].join('\n'),

  round2: [
    'You are auditing plugin code for security-sensitive spots. The deterministic static report',
    'is attached; the static verdict is authoritative and not yours to change. For THIS round:',
    'identify sensitive findings in the code.',
    '',
    'Produce ONLY a JSON object, no prose:',
    '{"findings":[{"category":"secret|exfiltration|telemetry|obfuscation|dangerous-api|other",',
    '  "evidence":"<quoted code, max 200 chars>","risk":"low|medium|high|critical",',
    '  "suggestion":"<how to fix, or remove if no legitimate use>"}]}',
    '',
    'Rules: category must be one of the enum values; evidence must be traceable to the code;',
    'if you find nothing, output an empty array — never invent findings.',
  ].join('\n'),

  round3: [
    'You are assessing the CODE QUALITY of a plugin (not its security verdict, which is set by',
    'the static layer). For THIS round: score five dimensions and an overall quality score.',
    '',
    'Produce ONLY a JSON object, no prose:',
    '{"dimensions":{"errorHandling":{"score":0-100,"note":"..."},',
    ' "boundaryChecks":{"score":0-100,"note":"..."},',
    ' "dependencies":{"score":0-100,"note":"..."},',
    ' "maintainability":{"score":0-100,"note":"..."},',
    ' "docs":{"score":0-100,"note":"..."}},',
    ' "qualityScore":<0-100, the average of the five dimensions>,',
    ' "qualityNotes":["<anything notable>"]}',
    '',
    'Rules: qualityScore must be the average of the five dimension scores; output valid JSON only.',
  ].join('\n'),

  round4: [
    'You are producing the FINAL audit summary for a plugin. You receive the outputs of the',
    'previous rounds (overview, security-sensitive findings, quality assessment) and the',
    'deterministic static report.',
    '',
    'The deterministic static verdict (critical/suspicious/clean) is authoritative and provided',
    'by rules, not by you. Do not change, soften, or relabel it. Your role is to add context.',
    '',
    'Produce ONLY a JSON object, no prose:',
    '{"llmFindings":[{"category":"secret|exfiltration|telemetry|obfuscation|dangerous-api|other",',
    '  "evidence":"<quoted code, max 200 chars>","risk":"low|medium|high|critical",',
    '  "suggestion":"<how to fix, or remove if no legitimate use>"}],',
    ' "qualityScore":<0-100>,',
    ' "confidence":"high|medium|low",',
    ' "summary":"<2-4 sentences, evidence-based>",',
    ' "recommendation":"approve|review|reject"}',
    '',
    'Rules: recommendation must weigh the static verdict first (critical ⇒ reject); output valid JSON only.',
  ].join('\n'),
} as const
